version: '3'

services:

  livy:
    build: .
    ports:
      - 8998:8998

  spark:
    build: ./spark
    volumes:
      - ./src:/src
  
  mssql:
      image: microsoft/mssql-server-linux:latest
      environment: 
          - ACCEPT_EULA=Y
          - SA_PASSWORD=YourStrong!Passw0rd
      ports:
          - 1433:1433
      volumes:
          - /var/opt/mssql